### ISSUE TITLE
java-md-doclet Build Failure

### ISSUE THREAD

**Issue by tusharkr18** [iotaledger/java-md-doclet#19]
Hello 
Based on the instructions, I tried running the maven install command but it failed

Can you please help as I am getting the same error while running the robot framework from terminal- Could not find artifact com.sun:tools:jar:6 at specified path /usr/local/Cellar/openjdk/15.0.2/libexec/openjdk.jdk/Contents/Home/../lib/tools.jar

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[19,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[20,38] package com.sun.javadoc.AnnotationDesc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[21,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[22,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[23,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[24,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[25,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[26,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[27,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[34,31] cannot find symbol
  symbol: class Doclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Parser.java:[3,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Parser.java:[4,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Parser.java:[5,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[53,21] cannot find symbol
  symbol:   class RootDoc
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[79,27] cannot find symbol
  symbol:   class ClassDoc
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[105,32] cannot find symbol
  symbol:   class Parameter
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[125,56] cannot find symbol
  symbol:   class MethodDoc
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/DocumentMethodAnnotation.java:[3,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[144,34] cannot find symbol
  symbol:   class ElementValuePair
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[162,33] cannot find symbol
  symbol:   class RootDoc
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[217,57] cannot find symbol
  symbol:   class DocErrorReporter
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/MDDoclet.java:[265,19] cannot find symbol
  symbol:   class LanguageVersion
  location: class org.iota.mddoclet.MDDoclet
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/DocumentMethodAnnotation.java:[12,13] cannot find symbol
  symbol:   class MethodDoc
  location: class org.iota.mddoclet.DocumentMethodAnnotation
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/DocumentMethodAnnotation.java:[19,37] cannot find symbol
  symbol:   class MethodDoc
  location: class org.iota.mddoclet.DocumentMethodAnnotation
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[9,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[10,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[11,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[12,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[13,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[14,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[15,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[16,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[17,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[18,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[19,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/example/Export.java:[6,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Parser.java:[44,48] cannot find symbol
  symbol:   class MethodDoc
  location: class org.iota.mddoclet.Parser
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Parser.java:[51,35] cannot find symbol
  symbol:   class MethodDoc
  location: class org.iota.mddoclet.Parser
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/example/Export.java:[22,32] cannot find symbol
  symbol:   class MethodDoc
  location: interface org.iota.mddoclet.example.Export
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/example/Export.java:[32,33] cannot find symbol
  symbol:   class MethodDoc
  location: interface org.iota.mddoclet.example.Export
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/example/Export.java:[42,33] cannot find symbol
  symbol:   class MethodDoc
  location: interface org.iota.mddoclet.example.Export
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/data/ReturnParam.java:[3,23] package com.sun.javadoc does not exist
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/data/ReturnParam.java:[15,17] cannot find symbol
  symbol:   class Type
  location: class org.iota.mddoclet.data.ReturnParam
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/data/ReturnParam.java:[32,54] cannot find symbol
  symbol:   class Type
  location: class org.iota.mddoclet.data.ReturnParam
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/data/ReturnParam.java:[50,16] cannot find symbol
  symbol:   class Type
  location: class org.iota.mddoclet.data.ReturnParam
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/data/ReturnParam.java:[78,31] cannot find symbol
  symbol:   class Type
  location: class org.iota.mddoclet.data.ReturnParam
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[48,44] cannot find symbol
  symbol:   class Type
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[67,29] cannot find symbol
  symbol:   class Type
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[79,33] cannot find symbol
  symbol:   class Type
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[83,35] cannot find symbol
  symbol:   class Tag
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[87,36] cannot find symbol
  symbol:   class Tag
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[87,12] cannot find symbol
  symbol:   class ClassDoc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[100,41] cannot find symbol
  symbol:   class Tag
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[100,53] cannot find symbol
  symbol:   class ClassDoc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[100,67] cannot find symbol
  symbol:   class MethodDoc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[152,42] cannot find symbol
  symbol:   class MethodDoc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[184,39] cannot find symbol
  symbol:   class ClassDoc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[188,44] cannot find symbol
  symbol:   class ClassDoc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[216,36] cannot find symbol
  symbol:   class Doc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[236,34] cannot find symbol
  symbol:   class Doc
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[253,28] cannot find symbol
  symbol:   class Tag
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[291,34] cannot find symbol
  symbol:   class SeeTag
  location: class org.iota.mddoclet.Util
[ERROR] /Users/tk/eclipse-workspace/java-md-doclet/src/main/java/org/iota/mddoclet/Util.java:[415,39] cannot find symbol
  symbol:   class TypeVariable
  location: class org.iota.mddoclet.Util

**Comment by kwek20** [comment]
Better late than never; You can only run this on Java 7 or less
