### ISSUE TITLE
Generalize methods/classes which we will generate

### ISSUE THREAD

**Issue by kwek20** [iotaledger/java-md-doclet#3]
Currently this plugin is hardcoded for IRI methods. Since it is just a Java method, we should generalize this Doclet to work for any java project. (For example iota-java library)

Required input: List of method names
Optional input:  List of classes, so we don't check every class

**Required output**
Libray: https://github.com/iotaledger/documentation/pull/94
IRI: https://github.com/iotaledger/iri/issues/1076

There are a few ways to go about this;
#### Enum
Pass an Enum to the Doclet using its full java class path in a string. This path will be parsed, the class loaded, and all en Enum values read. The Enum values will be all methods you wish to document.
Since IRI api methods are called `apiMethodStatement`, and the required output is `apiMethod`, we need to differentiate between function name and display name.

This can be done by adding multiple parameters to each Enum value, which could be function names. Then the `.equals()` method will be overriden and used to check if a method is an method we wish to document.

Downside of this method is that this Enum also needs to be updated whenever we make changes to the API, which can be forgotten. Unit tests can be written to ensure the Enum contains all API endpoints.
Another drawback of this is that another developer may change the Javadocs without understanding that it effects external API documentation. This could also be seen as a good thing since generation and writing should be independent, but might break the doclet.

_An Enum with all api methods would be good to have anyways, because we then have all the API method names in a single class, instead of scattered around (No magic string/integers are always good!). Possibly no longer relevant after iotaledger/iri#920_

Example doclet input:
```
<additionalOption>-methodlist "org.iota.ApiCall"</additionalOption>

public enum ApiCall {
	NODE_INFO("getNodeInfo"),
	GET_NEIGHBORS("getNeighbors"),
	ADD_NEIGHBORS("addNeighbors"),
	REMOVE_NEIGHBORS("removeNeighbors"),
	GET_TIPS("getTips");

        public boolean equals(Object name){
            return name.toString().equals(toString()) || name.toString().equals(toString() + "Statement");
        }
}
```

#### Annotation
Every method in the project you wish to have documented, should have an annotation. The annotation should specify what the display name should be in the documentation, so the actual function name does no longer matter.
This provides flexibility and readability since its right on the class. It is also easier to maintain since when you change the function, the annotation still supplies the same information. If you want to change the name, its right next to the function. 

Downside of this is that it would create a dependency to the Doclet, since we will define the Annotation there.

Example:
```
@GenMd("getNodeInfo")
public Response getNodeInfoStatement {
```

#### Raw list
We could supply the `-methods` with a space separated list in quotes. This wont have any dependencies at all, but will be annoying to maintain. Could be split with a `:` to have display name and function name separated 

Example:
```
<additionalOption>-methodlist "getNodeInfo:getNodeInfoStatement getNeighbors:getNeighborsStatement"</additionalOption>
```

#### Other ideas
Know a better way to solve this? Please comment!

## Different output
Since each project could require a different layout of the documented method, there should be a way to supply a template file.

This could either be done though an `additionalOption`, or all templates reside in the Doclet repo. Arguments for keeping all templates in the Doclet would be that the projects do not need to know how they are beeing displayed. It is also convenient for template inheritance to have them in a single space.

#### additionalOption example
```
<additionalOption>-templateFile "path/to/template.file"</additionalOption>
```

**Comment by GalRogozinski** [comment]
>An Enum with all api methods would be good to have anyways, because we then have all the API method names in a single class, instead of scattered around. (No magic string/integers are always good!)

If we implement https://github.com/iotaledger/iri/issues/920 it may be less necessary because we will create a clean class without too much noise. This will take a while though :sweat_smile: 

Another drawback of the enum is that another developer may change the javadocs without understanding that it effects external api documentation.

**Comment by GalRogozinski** [comment]
If we don't go for the annotations I think the enum should turn to a configuration file (yaml, ini, or etc.)

**Comment by kwek20** [comment]
I dont agree, I still think we will need an Enum with all API commands, whether this is references in a switch inside API.java, or with functional routing as proposed in https://github.com/iotaledger/iri/pull/392.
```
commandRoute.put("addNeighbors", addNeighbors());

VS

commandRoute.put(ApiCommand.ADD_NEIGHBOR, addNeighbors());
```
Any magic string is one too many, and any magic strings related to each other should have their own Enum.

The question is, what if we have something we wish to document which is not an API command.

**Comment by GalRogozinski** [comment]
I think the final design of the API should use JAX-RS (an issue that still needs to be groomed https://github.com/iotaledger/iri/issues/920):
So the end result will look like this:
```
@Get
@Path("getNodeInfo")
@GenMd
public AbstractResponse getNodeInfo() {
```

**Comment by kwek20** [comment]
Well in that case `@Path("getNodeInfo")` would be `@Path(ApiCommand.GET_NODE_INFO)`.
Whichever implementation, we will always need to have the command name somewhere. I would rather have it all contained in a single list/enum then spread out over methods/classes

**Comment by GalRogozinski** [comment]
Yeah it would be `ApiCommand.GET_NODE_INFO.toString()`
It would make more sense to create literal constants (`static final`)

Anyhows, in the end game API.java should consist only of small methods that do input validation that delegate complicated logic to other classes, so it will be much more decipherable.
